version: '3'
services:
  app:
    image: diet-app
    container_name: diet-app
    ports:
      - 80:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: "npm run start:dev"
    networks:
      - network

  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./mysql/dump/:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - network

networks:
  network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 255.255.255.0/24
